### ISSUE TITLE
404.html should be selfcontained.

### ISSUE THREAD

**Issue by deekoder** [miniohq/gluegun#10]
Short term solution: one 404.html with css and js links from vendor folder. 
Longterm solution: Generate 404.html from 404.erb

**Comment by kaankabalak** [comment]
#11 should fix this issue in the short term

**Comment by kaankabalak** [comment]
minio/gluegun#86 should fix this issue in the long term once merged

**Comment by kaankabalak** [comment]
Should be fixed by minio/gluegun#86
